/* $License$ */

/**
 * Generated market data model.
 * <p>
 * This package was generated by the <a href="http://help.eclipse.org/stable/index.jsp?topic=/org.eclipse.emf.doc/references/overview/EMF.html">Eclipse Modeling Framework</a>. 
 * 
 * @see org.marketcetera.photon.marketdata.IMarketData
 * 
 * @author <a href="mailto:will@marketcetera.com">Will Horn</a>
 * @version $Id: package-info.java 16154 2012-07-14 16:34:05Z colin $
 * @since 1.5.0
 */
package org.marketcetera.photon.model.marketdata;

